version: "3"

services:
  postgres:
    container_name: sculptor-postgres
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d sculptor -U sculptor_user']
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - sculptop-net
  sculptor:
    container_name: sculptor-bot
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "/image:/sculptop/data/image"
      - "/logs:/sculptop/logs"
      - "/models:/sculptor/models"
    networks:
      - sculptop-net
    restart: always

volumes:
  pgdata:
  image:
  logs:
  models:

networks:
  sculptop-net:
    driver: bridge